DjangoUeditor/urls.py
# -*- coding: utf-8 -*-
import django
from .views import get_ueditor_controller

DJANGO_VERSION = django.VERSION[:2]


if DJANGO_VERSION >= (1, 8):
    from django.conf.urls import url
    urlpatterns = [
        url(r'^controller/$', get_ueditor_controller)
    ]

else:
    try:
        from django.conf.urls import patterns, url
    except ImportError:
        from django.conf.urls.defaults import patterns, url

    urlpatterns = patterns('',
        url(r'^controller/$', get_ueditor_controller)
    )

XueXiTT/urls.py
import xadmin
from django.urls import path,include,re_path
from users.views import IndexView,Root
from django.views.static import serve
from XueXiTT.settings import MEDIA_ROOT,STATICFILES_DIRS

urlpatterns = [
    path('xadmin/', xadmin.site.urls),
    path('',IndexView.as_view(),name='index'),
    path('bdunion.txt/',Root.as_view(),name='root'),
    path('',include('users.urls')),
    path('',include('organization.urls')),
    path('captcha',include('captcha.urls')),
    re_path('media/(?P<path>.*)', serve, {'document_root':MEDIA_ROOT}),
    path('',include('course.urls')),
    re_path('static/(?P<path>.*)',serve,{'document_root':STATICFILES_DIRS}),
    path('ueditor/',include('DjangoUeditor.urls'))
]

handler404='users.views.page_not_found'
handler500='users.views.page_error'

apps/course/urls.py
from django.urls import path,re_path
from .views import CourseListView, CourseDetailView,CommentsView,AddCommentsView,VideoView,MoviePlay,MovieCommentsView,\
    PublicCourseView,UnityListView,UnrealListView,MachineLearningListView,DataScienceListView,MovieListView,PublicCourseListView
app_name = "course"

urlpatterns = [
    path('course_list/',CourseListView.as_view(),name='course_list'),
    re_path('course/(?P<course_id>\d+)/', CourseDetailView.as_view(), name="course_detail"),
    re_path('video/(?P<video_id>\d+)/', VideoView.as_view(),name='video_info'),
    re_path('course_public/(?P<course_id>\d+)/', PublicCourseView.as_view(),name='course_public'),
    path('public_list/', PublicCourseListView.as_view(),name='public_list'),
    path('movie_list/', MovieListView.as_view(),name='movie_list'),
    path('unity_list/', UnityListView.as_view(),name='unity_list'),
    path('unreal_list/', UnrealListView.as_view(),name='unreal_list'),
    path('machine_learning/', MachineLearningListView.as_view(),name='machine_learning'),
    path('data_science/', DataScienceListView.as_view(),name='data_science'),
    path('video_comments/', CommentsView.as_view(), name="video_comments"),
    re_path('movie/(?P<movie_id>\d+)/', MoviePlay.as_view(), name="movie_play"),
    path('add_comment/', AddCommentsView.as_view(), name="add_comment"),
    path('movie/comment',MovieCommentsView.as_view(),name='movie_comment'),
]

apps/organization/urls.py
from organization.views import OrgView,AddUserAskView

from django.urls import path,re_path
from .views import OrgHomeView,OrgCourseView,OrgTeacherView,OrgDescView,AddFavView,TeacherListView, TeacherDetailView
# from .views import TeacherListView,TeacherDetailView

# 要写上app的名字
app_name = "organization"

urlpatterns = [
    path('list/',OrgView.as_view(),name='org_list'),
    path('add_ask/', AddUserAskView.as_view(), name="add_ask"),
    re_path('home/(?P<org_id>\d+)/', OrgHomeView.as_view(), name="org_home"),
    re_path('org_course/(?P<org_id>\d+)/', OrgCourseView.as_view(), name="org_course"),
    re_path('desc/(?P<org_id>\d+)/', OrgDescView.as_view(), name="org_desc"),
    re_path('org_teacher/(?P<org_id>\d+)/', OrgTeacherView.as_view(), name="org_teacher"),
    path('add_fav/', AddFavView.as_view(), name="add_fav"),
    path('teacher/list/', TeacherListView.as_view(), name="teacher_list"),
    re_path('teacher/detail/(?P<teacher_id>\d+)/', TeacherDetailView.as_view(), name="teacher_detail"),

]

apps/users/urls.py
from django.urls import path,re_path
from . import views

app_name='users'

urlpatterns=[
    path('login/',views.LoginView.as_view(),name='login'),
    path('logout/',views.LogoutView.as_view(),name='logout'),
    path('register/',views.RegisterView.as_view(),name='register'),
    re_path('active/(?P<active_code>.*)/',views.ActiveUserView.as_view(),name='user_active'),
    re_path('reset/(?P<active_code>.*)/',views.ResetView.as_view(),name='reset'),
    path('forget/',views.ForgetPwdView.as_view(),name='forget_pwd'),
    path('modify_pwd',views.ModifyPwdView.as_view(),name='modify_pwd'),
    path('users/info/',views.UserInfoView.as_view(),name='user_info'),
    path('image/upload',views.UploadImageView.as_view(),name='image_upload'),
    path("update/pwd/", views.UpdatePwdView.as_view(),name='update_pwd'),
    path("sendemail_code/", views.SendEmailCodeView.as_view(), name='sendemail_code'),
    path("update_email/", views.UpdateEmailView.as_view(), name='update_email'),
    path("users/mycourse/", views.MyCourseView.as_view(),name='my_course'),
    path('users/my_message/', views.MyMessageView.as_view(), name="my_message"),
    path('myfav/org/', views.MyFavOrgView.as_view(), name="myfav_org"),
    path('myfav/teacher/',views.MyFavTeacherView.as_view(),name='myfav_teacher'),
    path('myfav/course/', views.MyFavCourseView.as_view(), name="myfav_course"),
]

apps/course/models.py
from django.db import models
from datetime import datetime
from organization.models import CourseOrg,Teacher
from DjangoUeditor.models import UEditorField
from users.models import UserProfile


class CourseCategory(models.Model):
    code=models.CharField('code',default='',max_length=10)
    desc=models.CharField('描述',default='',max_length=100)

    class Meta:
        verbose_name='课程类别'
        verbose_name_plural=verbose_name

    def __str__(self):
        return self.desc


class Course(models.Model):
    thumbnail=models.ImageField('缩略图', upload_to='img/%Y%M', default='img/default.png', max_length=100, null=True,
                              blank=True)
    degree_choice=(('junior','初级'),('high','中级'),('senior','高级'))
    name=models.CharField('课程名',max_length=50)
    desc=models.CharField('课程描述',max_length=500)
#    detail=models.TextField('课程详情')
    detail = models.TextField('课程详情',default='')
    degree=models.CharField('难度',choices=degree_choice,max_length=10)
    course_category=models.ForeignKey(CourseCategory,verbose_name='课程类别',null=True, blank=True, on_delete=models.CASCADE)
    students = models.IntegerField("学习人数", default=0)
    like_nums = models.IntegerField('收藏数', default=0)
    fav_nums=models.IntegerField('收藏数',default=0)
    image = models.ImageField('封面',upload_to='img/%Y%M',default='img/default.png', max_length=100, null=True, blank=True)
    click_nums=models.IntegerField('点击数',default=0)
    tag = models.CharField('课程标签', default='', max_length=10, null=True, blank=True)
    add_time=models.DateTimeField('添加时间',default=datetime.now)
    course_org = models.ForeignKey(CourseOrg, on_delete=models.CASCADE, verbose_name="所属机构", null=True, blank=True)
    teacher = models.ForeignKey(Teacher, verbose_name='讲师', null=True, blank=True, on_delete=models.CASCADE)
    is_banner = models.BooleanField('是否轮播', default=False)
    banner = models.ImageField('封面',upload_to='ban/%Y%M', max_length=100, null=True, blank=True)
    is_open=models.BooleanField('是否公开课', default=False)

    class Meta:
        verbose_name='课程'
        verbose_name_plural=verbose_name

    def __str__(self):
        return self.name

    def get_course_video(self):
        return self.video_set.all()

    def get_first_video(self):
        return self.get_course_video().first()

    def get_vd_nums(self):
        # 获取课程的章节数
        return self.video_set.all().count()

    get_vd_nums.short_description = '章节数'


class Video(models.Model):
    course=models.ForeignKey(Course,verbose_name='课程',on_delete=models.CASCADE)
    name=models.CharField('视频名',max_length=100)
    add_time=models.DateTimeField('添加时间',default=datetime.now)
    url = models.CharField('视频路径',max_length=1000)
    learn_times = models.IntegerField("学习时长(分钟数)", default=0)
    en_subtitle=models.FileField('英文字幕',upload_to='en_subtitle/%Y%M',null=True, blank=True)
    cn_subtitle = models.FileField('中文字幕', upload_to='cn_subtitle/%Y%M', null=True, blank=True)
    click_nums=models.IntegerField('点击数',default=0)

    class Meta:
        verbose_name='视频'
        verbose_name_plural=verbose_name

    def __str__(self):
        return self.name


class CourseResource(models.Model):
    course=models.ForeignKey(Course,verbose_name='课程',on_delete=models.CASCADE)
    name=models.CharField('视频名',max_length=100)
    add_time=models.DateTimeField('添加时间',default=datetime.now)
    download=models.FileField('资源文件',upload_to='course/resource/%Y/%m',max_length=100)

    class Meta:
        verbose_name='课程资源'
        verbose_name_plural=verbose_name

    def __str__(self):
        return self.name


class Movie(models.Model):
    thumbnail=models.ImageField('缩略图', upload_to='img/%Y%M', default='img/default.png', max_length=100, null=True,
                              blank=True)
    url=models.CharField('观看地址',max_length=500,default='')
    name = models.CharField('视频名', max_length=100)
    add_time = models.DateTimeField('添加时间', default=datetime.now)
    download = models.CharField('下载地址',max_length=500, null=True, blank=True)
    click_nums = models.IntegerField('点击数', default=0)

    class Meta:
        verbose_name='电影'
        verbose_name_plural=verbose_name

    def __str__(self):
        return self.name


class MovieComments(models.Model):
    user = models.ForeignKey(UserProfile, verbose_name='用户', on_delete=models.CASCADE)
    movie=models.ForeignKey(Movie, verbose_name='电影', on_delete=models.CASCADE)
    comments = models.CharField('评论', max_length=500)
    add_time = models.DateTimeField('添加时间', default=datetime.now)

    class Meta:
        verbose_name = '评论'
        verbose_name_plural = verbose_name

templates/active_fail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<p>链接失效</p>
</body>
</html>

templates/course-detial.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}课程详情{% endblock %}
{% block breadcrumb %}
   <li class="breadcrumb-item"><a href="{% url 'index' %}">Home</a></li>
    <li class="breadcrumb-item"><a href="{% url 'course:course_list' %}">课程列表</a></li>
        <li class="breadcrumb-item">课程详情</li>
{% endblock %}
{% block content %}
    <!-- Main content -->
    <section class="content">
      <div class="container-fluid">
          <div class="row">
          <div class="col-md-9">
            <!-- Box Comment -->
            <div class="card">
              <div class="card-header d-flex p-0">
                  <h3 class="card-title p-3">Tabs</h3>
                <!-- /.card-tools -->
              </div>
              <!-- /.card-header -->
              <div class="card-body">
                  <div class="row">
                    <div class="col-md-6">
                     <img class="img-fluid pad" style="padding: 0px 0px 20px 0px;" src="{{ MEDIA_URL }}{{ course.image }}" alt="Photo">
                     <br>
                    <button type="button" class="btn btn-default btn-sm"><i class="fa fa-share"></i> Share</button>
                    </div>
                    <div class="col-md-6 " style="padding: 0px 0px 0px 20px;" >
                          <dl>
                          <dt><h2>{{ course.name }}</h2></dt>
                          <dd>{{ course.desc }}</dd>
                          <dd>
                              <div class="card-footer card-comments">
                                难度：<strong><h2>{{ course.get_degree_display }}</h2></strong>
                                  <span class="text-muted float-right">收藏人数:{{ course.fav_nums }}</span>
                                </span><!-- /.username -->
                              </div>
                          </dd>
                          <dd>课程数：{{ course.get_vd_nums }}</dd>
                          <dd>课程类别：{{ course.category }}</dd>
                          <div class="row">
                            {% if request.user.is_authenticated %}
                              <div class="col-md-6">
                                 <button id="jsLeftBtn" type="button" class="btn btn-block btn-default btn-lg"> {% if has_fav_course %}已收藏{% else %}收藏{% endif %}</button>
                              </div>
                                {% else %}
                              <div class="col-md-6">
                                  <a href="{% url 'users:login' %}"><button class="btn btn-block btn-default btn-lg">开始学习</button></a>
                              </div>
                              {% endif %}
                          </div>
                        </dl>
                      </div>
                  </div>
              <br>
                <div class="card">
              <div class="card-header bg-info">
                <h3 class="card-title">课程详情</h3>
              </div>
              <div class="card-body">
                {{ course.detail | safe }}
              </div>
              <!-- /.card-body -->
            </div>
            {% if request.user.is_authenticated %}
                <div class="card">
                      <div class="card-header no-border">
                        <h3 class="card-title">课程列表</h3>
                      </div>
                      <div class="card-body">
                          {% for video in videos %}
                        <div class="d-flex justify-content-between align-items-center border-bottom mb-3">
                          <p class="text-info text-lg">
                            <a href="{% url 'course:video_info' video.id %}">{{ video.name }}</a>
                          </p>
                          <p class="d-flex flex-column text-right">
                            <span class="font-weight-bold">
                             <span class="text-muted">播放次数&nbsp;&nbsp;{{ video.click_nums }}</span>
                            </span>
                          </p>
                        </div>
                          {% endfor %}
                       </div>
                </div>
                {% endif %}
              </div>
              <!-- /.card-body -->
          <!-- /.col -->
          </div>
          </div>
              <div class="col-md-3">
              </div> <!-- /.container-fluid -->
      </div>
      </div>
    </section>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->
{% endblock %}

{% block custom_script %}
    <script type="text/javascript">
            function add_fav(current_elem, fav_id, fav_type){
            $.ajax({
                cache: false,
                type: "POST",
                url:"{% url "organization:add_fav" %}",
                data:{'fav_id':fav_id, 'fav_type':fav_type},
                async: true,
                beforeSend:function(xhr, settings){
                    xhr.setRequestHeader("X-CSRFToken", "{{ csrf_token }}");
                },
                success: function(data) {
                    if(data.status == 'fail'){
                        if(data.msg == '用户未登录'){
                            window.location.href="/login/";
                        }else{
                            alert(data.msg)
                        }

                    }else if(data.status == 'success'){
                        current_elem.text(data.msg)
                    }
                },
            });
        }
        $('#jsLeftBtn').on('click', function(){
            add_fav($(this), {{ course.id }}, 1);
        });
    </script>
{% endblock %}

templates/forgetpwd.html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
    {% load staticfiles %}
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>AdminLTE 3 | Registration Page</title>
  <!-- Tell the browser to be responsive to screen width -->
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <!-- Font Awesome -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
  <!-- Ionicons -->
  <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
  <!-- Theme style -->
  <link rel="stylesheet" href="{% static 'dist/css/adminlte.min.css' %}">
  <!-- iCheck -->
  <link rel="stylesheet" href="{% static 'plugins/iCheck/square/blue.css' %}">
  <!-- Google Font: Source Sans Pro -->
  <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
</head>
<body class="hold-transition register-page">
<div class="register-box">
  <div class="register-logo">
    <a href="{% url 'users:register' %}"><b>学习天堂</b></a>
  </div>

  <div class="card">
    <div class="card-body register-card-body">
      <p class="login-box-msg">找回密码</p>

      <form id="email_register_form" action="{% url 'users:forget_pwd' %}" method="post">
        <div class="form-group has-feedback">
          <input type="email" class="form-control has-error" placeholder="Email" name="email">
          <span class="fa fa-envelope form-control-feedback"></span>
        </div>
        <div class="row">
            <div class="col-12 offset-1">
           {{ register_form.captcha }}
          <!-- /.col -->
            </div>
        </div>
          <br>
        <div class="row">
            <!--
          <div class="col-8">
            <div class="checkbox icheck">
              <label>
                <input type="checkbox"> I agree to the <a href="#">terms</a>
              </label>
            </div>
          </div>
          -->
          <!-- /.col -->
          <div class="col-12">
            <button type="submit" class="btn btn-primary btn-block btn-flat">找回密码</button>
          </div>
          <!-- /.col -->
        </div>
          {% csrf_token %}
      </form>
<!--
      <div class="social-auth-links text-center">
        <p>- OR -</p>
        <a href="#" class="btn btn-block btn-primary">
          <i class="fa fa-facebook mr-2"></i>
          Sign up using Facebook
        </a>
        <a href="#" class="btn btn-block btn-danger">
          <i class="fa fa-google-plus mr-2"></i>
          Sign up using Google+
        </a>
      </div>
-->
      <a href="{% url 'users:login' %}" class="text-center">已有账号</a>
    </div>
     <div id="jsEmailTips">
        {{ msg }}
    </div>
    <!-- /.form-box -->
  </div><!-- /.card -->
</div>
<!-- /.register-box -->

<script src="{% static 'plugins/jquery/jquery.min.js' %}"></script>
<!-- Bootstrap 4 -->
<script src="{% static 'plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<!-- iCheck -->
<script src="{% static 'plugins/iCheck/icheck.min.js' %}"></script>
<script>
  $(function () {
    $('input').iCheck({
      checkboxClass: 'icheckbox_square-blue',
      radioClass   : 'iradio_square-blue',
      increaseArea : '20%' // optional
    })
  })
</script>
<script src="{% static 'dist/js/myjs.js' %}"  type="text/javascript"></script>
</body>
</html>

templates/index.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block breadtitle %}学习天堂|在线教程{% endblock %}
{% block breadcrumb %}
   <li class="breadcrumb-item"><a href="{% url 'index' %}">Home</a></li>
{% endblock %}
{% block content %}
    <!-- Main content -->
    <section class="content">
      <div class="container-fluid">
        <div class="row">
          <!-- /.col -->
          <div class="col-md-9">
            <div class="card">
              <div class="card-body">
                <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
                  <ol class="carousel-indicators">
                    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
                    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
                    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
                  </ol>
                {% if banner_first %}
                  <div class="carousel-inner">
                    <div class="carousel-item active">
                         <a href="{% url 'course:course_detail' banner_first.id %}" >
                        <span class="mailbox-attachment-icon has-img">
                      <img class="d-block w-100" src="{{ MEDIA_URL }}{{ banner_first.banner }}" alt="First slide" height="300">
                        </span>
                         </a>
                    </div>
                      {% for course in list_banner %}
                    <div class="carousel-item">
                    <a href="{% url 'course:course_detail' course.id %}" >
                        <span class="mailbox-attachment-icon has-img">
                      <img class="d-block w-100 " src="{{ MEDIA_URL }}{{ course.banner }}" alt="Second slide" height="300">
                        </span>
                    </a>
                    </div>
                      {% endfor %}
                  </div>
                {% endif %}
                  <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    <span class="sr-only">Previous</span>
                  </a>
                  <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    <span class="sr-only">Next</span>
                  </a>
                </div>
              </div>
              <!-- /.card-body -->
            </div>
            <!-- /.card -->
          </div>
        <div class="col-md-3">
            <div class="card card-warning">
              <div class="card-header">
                <h3 class="card-title">点击广告赞助本站</h3>
                <div class="card-tools">
                  <button type="button" class="btn btn-tool" data-widget="collapse"><i class="fa fa-minus"></i>
                  </button>
                </div>
                <!-- /.card-tools -->
              </div>
              <!-- /.card-header -->
              <div class="card-body">
                  <a data-type="2" biz-keyword="电脑" data-tmpl="220x290" data-tmplid="9" data-rd="2" data-style="2" data-border="1" href="#"></a>
              </div>
              <!-- /.card-body -->
            </div>
            <!-- /.card -->
          </div>
            <div class="col-md-12">
                  <a target="_black" href="https://s.click.taobao.com/t?e=m%3D2%26s%3Ddevq%2BiAN8TIcQipKwQzePCperVdZeJviEViQ0P1Vf2kguMN8XjClAu5N8Xi7d1lH4CZyur93miVv1qWNbEBpmPrdFCQUhtDOlSB8iQJCuN1Hv4jsEH1NGU%2Fu2BptvxUXrnF3ShV1XeF8isIqg9litAZn%2By0keumoxJ%2BuUEnJYcOEEQepqblm8luaay6PHEO8NIH3xTvu0eIcJ965jhCBMByz1mcJG%2F2qRZujRnIpwuLGJe8N%2FwNpGw%3D%3D">
                      <span class="mailbox-attachment-icon has-img"><img src="{% static 'dist/img/ECS/1200-120.jpg' %}"></span>
                  </a>
            </div>
        <!-- /.row -->
        <!-- END ACCORDION & CAROUSEL-->
      </div>
        </div>
      <div class="container-fluid">
        <!-- COLOR PALETTE -->
        <!-- Recommended -->

       <div class="card card-default color-palette-box">
          <div class="card-header">
            <h3 class="card-title">
              <i class="fa fa-play-circle"></i>
              最新课程
            </h3>
            <div class="card-tools">
                  <a href="{% url 'course:course_list' %}" class="text-muted">查看更多&nbsp;&nbsp;</a>
                  <button type="button" class="btn btn-tool" data-widget="collapse"><i class="fa fa-minus"></i>
                  </button>
             </div>
          </div>
          <div class="card-body">
            <div class="row">
                {% for course in courses %}
               <div class="col-xl-2 col-lg-3 col-md-4 col-sm-6">
                <a href="{% url 'course:course_detail' course.id %}" ><span class="mailbox-attachment-icon has-img"><img src="{{ MEDIA_URL }}{{ course.thumbnail }}" alt="Attachment"></span></a>
                  <div class="mailbox-attachment-info">
                    <a href="{% url 'course:course_detail' course.id %}" class="mailbox-attachment-name">{{ course.name }}</a>
                        <span class="mailbox-attachment-size">
                          <a href="#" class="mailbox-attachment-name"><h6>{{ course.teacher.name }}</h6></a>
                        </span>
                  </div>
              </div>
                {% endfor %}
            </div>
          </div>
        </div>

        <div class="card card-default color-palette-box">
          <div class="card-header">
            <h3 class="card-title">
              <i class="fa fa-star"></i>
              公开课
            </h3>
              <div class="card-tools">
                  <a href="{% url 'course:public_list' %}" class="text-muted">查看更多&nbsp;&nbsp;</a>
                  <button type="button" class="btn btn-tool" data-widget="collapse"><i class="fa fa-minus"></i>
                  </button>
                </div>
          </div>
          <div class="card-body">
            <div class="row">
                {% for course in open_courses %}
                <div class="col-xl-2 col-lg-3 col-md-4 col-sm-6">
                <a href="{% url 'course:course_public' course.id %}" ><span class="mailbox-attachment-icon has-img"><img src="{{ MEDIA_URL }}{{ course.thumbnail }}" alt="Attachment"></span></a>
                  <div class="mailbox-attachment-info">
                    <a href="{% url 'course:course_public' course.id %}" class="mailbox-attachment-name">{{ course.name }}</a>
                        <span class="mailbox-attachment-size">
                          <a href="#" class="mailbox-attachment-name"><h6>{{ course.teacher.name }}</h6></a>
                        </span>
                  </div>
              </div>
                {% endfor %}
            </div>
          </div>
        </div>

        <div class="card card-default color-palette-box">
          <div class="card-header">
            <h3 class="card-title">
              <i class="fa fa-play-circle"></i>
              推荐课程
            </h3>
            <div class="card-tools">
                  <a href="{% url 'course:course_list' %}" class="text-muted">查看更多&nbsp;&nbsp;</a>
                  <button type="button" class="btn btn-tool" data-widget="collapse"><i class="fa fa-minus"></i>
                  </button>
             </div>
          </div>
          <div class="card-body">
            <div class="row">
                {% for course in recommend %}
               <div class="col-xl-2 col-lg-3 col-md-4 col-sm-6">
                <a href="{% url 'course:course_detail' course.id %}" ><span class="mailbox-attachment-icon has-img"><img src="{{ MEDIA_URL }}{{ course.thumbnail }}" alt="Attachment"></span></a>
                  <div class="mailbox-attachment-info">
                    <a href="{% url 'course:course_detail' course.id %}" class="mailbox-attachment-name">{{ course.name }}</a>
                        <span class="mailbox-attachment-size">
                          <a href="#" class="mailbox-attachment-name"><h6>{{ course.teacher.name }}</h6></a>
                        </span>
                  </div>
              </div>
                {% endfor %}
            </div>
          </div>
        </div>

        <div class="card card-default color-palette-box">
          <div class="card-header">
            <h3 class="card-title">
              <i class="fa fa-play-circle"></i>
              电影推荐
            </h3>
            <div class="card-tools">
                  <a href="{% url 'course:movie_list' %}" class="text-muted">查看更多&nbsp;&nbsp;</a>
                  <button type="button" class="btn btn-tool" data-widget="collapse"><i class="fa fa-minus"></i>
                  </button>
             </div>
          </div>
          <div class="card-body">
            <div class="row">
                {% for mov in movie %}
               <div class="col-xl-2 col-lg-3 col-md-4 col-sm-6">
                <a href="{% url 'course:movie_play' mov.id %}" ><span class="mailbox-attachment-icon has-img"><img src="{{ MEDIA_URL }}{{ mov.thumbnail }}" alt="Attachment"></span></a>
                  <div class="mailbox-attachment-info">
                    <a href="{% url 'course:movie_play' mov.id %}" class="mailbox-attachment-name">{{ mov.name }}</a>
                        <span class="mailbox-attachment-size">
                          <h6>添加时间： {{ mov.add_time }}</h6>
                        </span>
                  </div>
              </div>
                {% endfor %}
                <div class="col-md-12">
                  <a target="_black" href="https://s.click.taobao.com/t?e=m%3D2%26s%3DDas1fcl%2BTLkcQipKwQzePCperVdZeJviEViQ0P1Vf2kguMN8XjClAkjR1mEp1GIYL8PtxxJsl4lv1qWNbEBpmPrdFCQUhtDOlSB8iQJCuN2iR9KyufLv5FH%2FhwblmzC5rnF3ShV1XeF8isIqg9litAZn%2By0keumoxJ%2BuUEnJYcOEEQepqblm8luaay6PHEO80Hd8emvjIz26owIDioOK5ootqEvh1MawIYULNg46oBA%3D">
                      <span class="mailbox-attachment-icon has-img"><img src="{% static 'dist/img/aliyun/1200-120.jpg' %}"></span>
                  </a>
                </div>
              <div>
              </div>
            </div>
          </div>
        </div>

      </div>
      </div>
    </section>
{% endblock %}
</div>